[bq_credentials]
type = "service_account"
project_id = "meatloaf-427522"
private_key_id = "027bde2635c1cfcc7281328d4fb702723cfca132"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCi//cMPWVOYi1T
n8C3YHK3EvddFb4YTkLkmNj65diRIWE0AblCzLyMs2/VHY5pAku3xFF59dU6AR2H
ul5UF2RmYvZr3E73wsF41JB6GjqyDinuEV/gqL1lnnAtxBzrEHp/W1MCSqL7tTk4
DLvmhsjKVT8R4zSrxkNCt3RzXTSMQcOj6xMDbihH/28nECQOnJs/QuthgaEsasI1
4kobs5Uxl4dajOp5DmIQJ7uJJLpRgJLl5eSkQqeoHAXQDRCSiUlj3XjT0q8jOT0q
ZmB9pZM2REsa0AjaSqYb65qx35zoe4EO3ZCnwAfSoWKNo2Y/rk1t/wK5WWDAMUgL
tmnQraitAgMBAAECggEABnFktASnQPprfT820GjNEAR9Z54I5hAN39hU11IHhfES
VQpuZsAOAefD12I0M11mXcyyRcZcV88cejV5LgzAqLVntSq/qlZ17E9GqLTptgkO
Sj1Ak3JIDkC9gWmblQUROoCDHveRSq7GpLsIIFwairjk5dGbzuBm3ze+MCMyhQqy
Qhl0U7fLt4vfdWFmW6BYP+KFhwOzy+BHGNKDA6KLOm3nuPQLs1994B+reo1OU1xo
XFkW/WcRNXmo8ANM6ewz90bV91stbTmxmC1u6hmneBM8C2ix22aV3Ao/FvxRk/Vj
wZm4B+aJnD4PxAawqVfauCdXWfBoVL1v63tDLWMRRwKBgQDYvcLZl+WhkxmKesti
riBvniF/fovkDG742oMsy48ZCRpHMi7g54ZtstDdKRhGmEawkMJpWS6IJyOGtwEe
tjIlIkVo3rTTDMnKF/ezb1LOdpz8yOHQ6biwpG6rU4RhrbLGm+6bvvwlfbbI+pTK
M5wQqo2p/ssFKCaaxMzVeDxLpwKBgQDAhjqQK1X8H54ZH2kyhrWZQBv+rxrQ4bfM
m7G/Ejly67/kN5vil0sOJVoR/PNpoIv72ls7zO0HFyUGUcv24OySi1XTwWsPyA6f
AuoYq6RjofyT+c54XNYFnKKGMsjeaGTYydmyY8rmQcb5Od+/xKuamEBUgEZKFnVw
XGNpfbljiwKBgQC2RU85wj4A1T4jcQTdpeXtOCSfnYJzc+lXKhwqbb2XpkoNGazG
wq4QTtLLSqX5qFG6ZuK3yaISKif8QKaWd05QYDPS74dN/XEtnV5X7gTLUIDRLPaK
xCLnmkDfn8qygmrYD4ZoQAK4XLJ87g52xVQ3x9Z+4aFGYu+kNGC2HPlH/QKBgCjx
IqkgHiQE0UlEbcmp7hqOEKYDtO8w4TZo8c7RYFg5HFC7JrJ0PCjg9puWsGkJFFvV
3ssD1HBKkrwaTwbMZGLxsKncmxj7EWjtZL0kW0w42Y7ac/cSvwzod4OUbzUk/DVC
D8KpCDAZUugTT6rndxrkP+H4eXot9oGTlCyN6QvrAoGAY+HErJ8tCBnhC/G6tefV
YnYXL3A0XtAjW9F+wGrtZVHIHYXK7+m+v3eWFCgeA/UlehkeZ9/uG/IGTH7RdkOM
kfbQtMpkUuZuaa2EMRwhz4N9nm8Cdpkwj5hnbQFKrpsO2T9bWg+XFN+LsKKyhmgC
t5ZyXbC9IV+OYD/bjg1pt4E=
-----END PRIVATE KEY-----"""
client_email = "jondomino@meatloaf-427522.iam.gserviceaccount.com"
client_id = "113069606501771315115"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/jondomino%40meatloaf-427522.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

